name: Hello-World Workflow

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    say-hello-world-inline:
        runs-on:
            ubuntu-latest
        steps:
            - name: Say Hello World Inline
              run: echo "Hello, World!"